version: '2'
services:
  webapp:
    image: 419357440556.dkr.ecr.us-east-1.amazonaws.com/blooddonationproject-repo:v3
    cpu_shares: 1023
    mem_limit: 980MB
    ports:
      - "8081:8091"
    command: bash -c "dotnet BloodDonationProject.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8091
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs5.papertrailapp.com:39389"